const ROLES = {
  CLIENT: "CLIENT",
  PROFESSIONAL: "PROFESSIONAL",
  EMPLOYEE: "EMPLOYEE",
  HR: "HR",
  ADMIN: "ADMIN",
};

const VERIFICATION_STATUS = {
  PENDING: "PENDING",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
};

const COMPLAINT_STATUS = {
  OPEN: "OPEN",
  IN_REVIEW: "IN_REVIEW",
  IN_PROGRESS: "IN_PROGRESS",
  ESCALATED: "ESCALATED",
  RESOLVED: "RESOLVED",
};

const ADMIN_REQUEST_TYPES = {
  VERIFICATION: "VERIFICATION",
  APPOINTMENT: "APPOINTMENT",
};

module.exports = { ROLES, VERIFICATION_STATUS, COMPLAINT_STATUS, ADMIN_REQUEST_TYPES };

